setup.py: bump required numpy version from 1.10 to 1.13
Due to a possible bug with using dask and numpy:

    ValueError: Inferred dtype from function 'lt' was
    'bool' but got 'float64', which can't be cast using casting='same_kind'

Occurred when using mask_array with PixelatedSTEM.find_hot_pixels.